### ISSUE TITLE
Cannot list all versions

### ISSUE THREAD

**Issue by jeffrey-aguilera** [crukci-bioinformatics/clarityclient#9]
I would expect that `api.listAll(com.genologics.ri.version.Version.class)` would enumerate all the api versions at `/api/`; instead, a runtime exception is thrown:
```
java.lang.IllegalArgumentException: The class com.genologics.ri.version.Version has not been annotated with the GenologicsEntity annotation.
  at org.cruk.genologics.api.impl.GenologicsAPIImpl.checkEntityAnnotated(GenologicsAPIImpl.java:806)
  at org.cruk.genologics.api.impl.GenologicsAPIImpl.listAll(GenologicsAPIImpl.java:1171)
  at org.cruk.genologics.api.impl.GenologicsAPIImpl$$FastClassBySpringCGLIB$$970a60c7.invoke(<generated>)
  at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
  at org.springframework.aop.aspectj.AspectJAfterAdvice.invoke(AspectJAfterAdvice.java:47)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
  at org.springframework.aop.aspectj.AspectJAfterAdvice.invoke(AspectJAfterAdvice.java:47)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
  at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
  at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
  at org.cruk.genologics.api.impl.GenologicsAPIImpl$$EnhancerBySpringCGLIB$$9f8cbec0.listAll(<generated>)
  ... 32 elided
```
Although the entity is `Locatable`, it does not have a @GenologicsEntity annotation.

**Comment by rich7409** [comment]
Ah yes, the versions are a bit odd. The Clarity client is built on the v2 API spec from Genologics/Illumina, and the version of the API used is fixed at v2. Using anything else will need new classes and JAXB mappings (probably). The "versions" end point is under "/api", not "/api/v2", and as such isn't available through the client.

The "Version" and "Versions" classes are there because they're created (originally) from the XSD file but they're not practicably usable against the API using the client. As such, "Version" isn't an entity under the v2 API.

**Comment by rich7409** [comment]
Ah yes, the versions are a bit odd. The Clarity client is built on the v2 API spec from Genologics/Illumina, and the version of the API used is fixed at v2. Using anything else will need new classes and JAXB mappings (probably). The "versions" end point is under "/api", not "/api/v2", and as such isn't available through the client.

The "Version" and "Versions" classes are there because they're created (originally) from the XSD file but they're not practicably usable against the API using the client. As such, "Version" isn't an entity under the v2 API.
